CREATE TABLE SUPERHEROES (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100),
    pseudonym VARCHAR(100),
    publisher VARCHAR(100),
    firstAppearance DATETIME
);

CREATE TABLE SKILLS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    skill VARCHAR(100),
    superheroId INT,
    FOREIGN KEY (superheroId) REFERENCES SUPERHEROES(id) ON DELETE CASCADE
);

CREATE TABLE ALLIES (
    id INT PRIMARY KEY AUTO_INCREMENT,
    ally VARCHAR(100),
    superheroId INT,
    FOREIGN KEY (superheroId) REFERENCES SUPERHEROES(id) ON DELETE CASCADE
);

CREATE TABLE USERS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) UNIQUE,
    password VARCHAR(100)
);

CREATE TABLE USER_ROLES (
    id INT PRIMARY KEY AUTO_INCREMENT,
    role VARCHAR(100),
    userId INT,
    FOREIGN KEY (userId) REFERENCES USERS(id) ON DELETE CASCADE
);