CREATE TABLE SUPERHEROES (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100),
    pseudonym VARCHAR(100),
    publisher VARCHAR(100),
    firstAppearance DATETIME
);

CREATE TABLE SKILLS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    skill VARCHAR(100),
    superheroId INT,
    FOREIGN KEY (superheroId) REFERENCES SUPERHEROES(id) ON DELETE CASCADE
);

CREATE TABLE ALLIES (
    id INT PRIMARY KEY AUTO_INCREMENT,
    ally VARCHAR(100),
    superheroId INT,
    FOREIGN KEY (superheroId) REFERENCES SUPERHEROES(id) ON DELETE CASCADE
);